name: Check for new resources

on:
  workflow_dispatch

jobs:
  run_update:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/resources-automated'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2


      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20' 

      - name: Install dependencies
        run: |
         cd sync
         npm install 

      - name: Run script
        run: |
         cd sync
         node src/main.js "${{ secrets.GITHUB_TOKEN }}"

      - name: Create PR
        run: |
         gh add resources.json
         gh commit -m "Automated resource updates"
         gh push -u origin HEAD:resources-automated
         gh pr create -B resources -H resources-automated --title 'Automated Resource update'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
