name: Check for new resources

on:
  workflow_dispatch:
  push:
    branches:
      - resources-automated
  schedule:
      - cron: '0 0 * * *'

jobs:
  run_update:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/resources-automated'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2


      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20' 

      - name: Install dependencies
        run: |
         cd sync
         npm install 

      - name: Run script
        run: |
         cd sync
         node src/main.js "${{ secrets.GITHUB_TOKEN }}"

      - name: Check for existing PR
        id: check_pr
        run: |
            pr_exists=$(gh pr list --base resources --head resources-automated --json number --jq 'length')
            echo "PR_EXISTS=$pr_exists" >> $GITHUB_OUTPUT
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create or update branch
        run: |
          git config user.name "${{ secrets.GIT_USER_NAME }}"
          git config user.email "${{ secrets.GIT_USER_EMAIL }}"
          git add resources.json
          git commit -m "Automated resource updates"
          git push -u origin resources-automated --force
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}


      - name: Create PR
        if: steps.check_pr.outputs.PR_EXISTS == '0'
        run: |
          gh pr create -B resources -H resources-automated --title 'Automated Resource update'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
